export const SubMenuConstants = [
  {
    title: "Book Seat",
    path: "/hotel_booking/book_seat",
  },
  { title: "Book Food",
   path: "/hotel_booking/book_food" },
  { title: "Hotel Details",
   path: "/hotel_booking/hotel_details" },
  //  {
  //   title: "Book Seat",
  //   path: "/home/book_seat",
  // },
  // { title: "About",
  //  path: "/home/about" },
  // { title: "Contact Us",
  //  path: "/home/contact_us" },
  //  {
  //   title: "Book Seat",
  //   path: "/home/book_seat",
  // },
  // { title: "About",
  //  path: "/home/about" },
  // { title: "Contact Us",
  //  path: "/home/contact_us" },
  //  {
  //   title: "Book Seat",
  //   path: "/home/book_seat",
  // },
  // { title: "About",
  //  path: "/home/about" },
  // { title: "Contact Us",
  //  path: "/home/contact_us" },
  //  {
  //   title: "Book Seat",
  //   path: "/home/book_seat",
  // },
  // { title: "About",
  //  path: "/home/about" },
  // { title: "Contact Us",
  //  path: "/home/contact_us" },
  //  {
  //   title: "Book Seat",
  //   path: "/home/book_seat",
  // },
  // { title: "About",
  //  path: "/home/about" },
  // { title: "Contact Us",
  //  path: "/home/contact_us" },
];
